spring:
  application:
    name: demeter-api
  servlet:
    multipart:
      max-request-size: 40MB
      max-file-size: 40MB
server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      buffered: true
      directory: /app/logs
      file-date-format: .yyyy-MM-dd
      pattern: '%t %a %A %m %U%q %s %I %B %D'
      prefix: access_log
      suffix: .log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true

retrofit:
  endpoints:
    - identity: ehr
      baseUrl: http://ehrnew.ziroom.com/
    - identity: ehrapi
      baseUrl: http://ehr-api.kp.ziroom.com/
    - identity: storage
      baseUrl: http://storage.kp.ziroom.com/
    - identity: ca
      baseUrl: http://ca.kp.ziroom.com/
    - identity: omega
      baseUrl: http://omega-api.kp.ziroom.com/
    - identity: worktop
      baseUrl: http://management-api.kp.ziroom.com/
  connection:
    connect-timeout: 5000
    read-timeout: 20000
    write-timeout: 20000
    max-idle-connections: 5
    keep-alive-duration: 5
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  root:
#    level: debug

message:
  baseUrl: http://message.ziroom.com
  token:
    workWechat: 60de7d18bd5d033440f35eff
  model:
    workWechat: WW-1625193835

halo:
  user-perm:
    app-code: demeter-api
    url: http://tech.halo.ziroom.com/api/v2/user-perm
