spring:
  application:
    name: demeter-api
server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      buffered: true
      directory: /app/logs
      file-date-format: .yyyy-MM-dd
      pattern: '%t %a %A %m %U%q %s %I %B %D'
      prefix: access_log
      suffix: .log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true

retrofit:
  endpoints:
    - identity: ehr
      baseUrl: http://ehrnew.t.ziroom.com/
    - identity: ehrapi
      baseUrl: http://ehr-api.ziroom.com/
  connection:
    connect-timeout: 5000
    read-timeout: 20000
    write-timeout: 20000
    max-idle-connections: 5
    keep-alive-duration: 5
mybatis:
  mapper-locations: classpath:mappers/*.xml

#logging:
#  root:
#    level: debug
